resistance2/travely-server

src/api/travel/travel.route.ts
=> feat: 여행 관리 api 기능 수정 (#27)

src/api/travel/travel.route.ts, src/db/schema.ts
- /manage-my-travel-teams/travelId 새 API 엔드포인트 추가 #33
- /my-created-travels/:userId API 수정 #29
=> feat: 내가 만든 여행  API, 여행 관리  API 수정 #29 #33

src/api/travel/travel.route.ts
- 페이지네이션 페이지가 0이 아닌 1페이지부터 시작하도록 수정
=> fix:  manage-my-travel 페이지네이션 수정

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/feat.yml, .github/ISSUE_TEMPLATE/refactor.yml, .github/ISSUE_TEMPLATE/setting.yml, .github/ISSUE_TEMPLATE/test.yml
=> docs: 이슈 템플릿 수정

src/api/travel/travel.route.ts
=> feat: travel-list api 추가 #35

src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts, src/app.ts, src/db/schema.ts
- travelGuide.route.ts 새 라우트 주소 추가
- GET {{origin}}/v1/travels-guide api 추가
=> feat: 여행 목록 조회(가이드 구해요) api 추가 #35

.github/workflows/server_cicd.yml
- rsync를 사용하여 변경된 파일만 전송
- 백업 과정에 디렉토리 체크 로직 추가
- 불필요한 중간 디렉토리 제거
=> fix: server-cicd workflow #43

.github/workflows/server_cicd.yml
=> fix: server-ci/cd 오타 수정  #43

src/db/schema.ts
=> feat: 여행 추가 API  #47

src/api/travel/travel.route.ts
- 여행 조회 API 수정
- response 데이터 수정
=> fix: 여행 조회 API 수정(여행자 구해요) #49

src/api/travel/travel.route.ts, src/checkRequiredFields.ts, src/db/schema.ts
- checkRequiredFieldsQuery, 입력 받은 매개변수 파라미터가 body에 있는지 없는지를 체크하도록 수정
- 여행 활성화 API가 isActive라는 query params를 받았을 때 오류가 발생하지 않도록 수정.
=> fix: checkRequiredField 수정, 여행 활성화 API 버그 수정

src/checkRequiredFields.ts
=> fix: src/checkRequiredFields 수정

src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts
=> fix: userId 없이도 여행 조회 api사용가능하게함

src/api/travel/travel.route.ts
- userId=null일 때도 travl-list api 가능하게
=> fix: travel-list api 수정, null userId

.vscode/settings.json, src/api/travel/TravelDetailData.ts, src/api/travel/travel.route.ts, src/db/schema.ts
- travel-detail에 상세 리뷰 리스트와 승인 유저 항목들이 나오도록 수정
=> Fix: travel-detail에 상세 리뷰 리스트와 승인 유저 항목들이 나오도록 수정

src/api/travel/travel.route.ts, src/db/schema.ts
PATCH v1/travels/bookmark 에서 북마크 삭제/추가가 가능하도록 수정
=> feat: bookmark api 수정  #81

src/api/review/review.routes.ts, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts, src/api/user/user.routes.ts, src/checkRequiredFields.ts
=> feat: 여행팀에 유저 등록 API추가 #82

src/api/review/review.routes.ts, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts, src/db/schema.ts, src/validChecker.ts
- 제목, 본문, 유저, 여행아이디 값을 기반으로 리뷰를 생성
{{origin}}/v1/reviews
=> feat: 여행 리뷰 생성 API#86

src/api/review/review.routes.ts
- 해당 유저가 작성한 review 목록을 가져오는 api
- 페이지네이션
=> feat: review 목록 조회 api #86

src/api/user/user.routes.ts, src/api/user/user.service.ts
- put /v1/users/phone api 추가
- put /v1/users/mbti api 추가
=> feat: 유저 개인 정보 변경 api 추가 #96

src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts
- response 값에 포함된 travels 라는 리스트에 각 요소들에 고유 아이디 값
id를 포함시킴
- skip 키워드를 사용해서 페이지네이션 로직을 수정
=> hotFix: 여행 리스트 조회 api 2개 수정

biome.json, lefthook.yml, package.json, src/api/imageUpload/image.routes.ts, src/api/imageUpload/imageUpload.ts, src/api/review/review.routes.ts, src/api/user/user.routes.ts, src/api/user/user.service.ts, src/app.ts, src/checkRequiredFields.ts, src/db/schema.ts, src/public/My Project.openapi.json, src/validChecker.ts, test.reviews.json
- lefthook 에서 bun run lint -> bun run check로 수정
=> fix: lefthook 설정 수정 #99

.vscode/settings.json, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts
=> settings: save on biome format#99

src/api/review/review.routes.ts, src/api/travel/travel.route.ts, src/db/schema.ts
- 해당 여행을 다녀오고, 해당 여행팀에 속한 유저만 리뷰를 달수 있도록 수정
- 여행 리뷰를 작성하면서 해당 여행 가이드에 대한 리뷰를 작성할 수 있도록 수정
=> fix: 리뷰 작성 API 유효성 검증 #90

src/api/travelGuide/travelGuide.route.ts
- get travels-guide/travel-list comment count error fix
- 삭제된 댓글은 집게 안되게하도록 수정
=> fix: comment count error

src/api/travel/travel.route.ts, src/public/My Project.openapi.json
=> fix: travel-deatil api fix

src/api/travel/travel.route.ts, src/convert.ts
- tagType 에 명시된 타입들로 tag들이 들어가게 수정
=> feat: 북마크리스트 api 수정

src/api/review/review.routes.ts, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts
- 여행 삭제 api
- 여행 (가이드 구해요) 삭제 api
- 삭제 된 글은 카운트 되지 않도록함.
- 관련 팀도 삭제되도록 설정`
=> feat: delete travel and delete travel-guide  #124

src/api/travel/travel.route.ts
=> fix: response에 isTraveler: boolean 추가 #131

src/api/travel/travel.route.ts
- 내가 만든 여행들에 참여한 여행자들중 아직 waiting상태인 총 유저수를
가져오는 api를 생성
=> feat: traveler waiting count api

src/api/travel/travel.route.ts, src/public/My Project.openapi.json
- 내가 참여한 여행 페이지에서도 페이지네이션이 되도록 api를 수정
=> fix: travels/my-travel api  #134

src/api/review/review.routes.ts, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts, src/api/user/user.routes.ts, src/api/user/user.service.ts
- **fix: review post api #138**
- **fix: userScore calculate  #138**
- **refactor: userRouter fix**
- **fix: travels-guide/travel-list api  #138**
- 목데이터가 아닌 실제 유저(가이드 별점)을 response값에 보내도록 수정
=> [fix] 여행 리뷰 작성 api 수정, 유저 리뷰 계산 방식 수정

src/api/travel/travel.route.ts, src/validChecker.ts
- feat: add isValidObjectId
- fix: check isValidObjectId
=> fix: check isValidObjectId

src/api/travel/travel.route.ts
- fix: travel-detail api
- 여행 조회시 userId가 없을 때도 조회가 가능하게함
=> hotfix: travel-detail

src/api/travel/travel.route.ts
=> fix: 완료된 여행의 여행자 waiting 수는 제외하도록함.

src/api/travel/bookmark.service.ts, src/api/travel/travel.route.ts, src/api/travelGuide/travelGuide.route.ts, src/db/schema.ts
- bookmark.service.ts에서 bookmark수, bookmark 여부, bookmark 리스트를 가져오는 메서드들을 정의함
- bookmark 컬렉션으로 새로 정의함
=> fix: 북마크가 북마크 최신 순으로 정렬

src/api/travel/bookmark.service.ts
=> fix: 삭제된 여행의 북마크는 가져오지 않도록함

src/api/bookmark/bookmark.service.ts, src/api/travel/travel.route.ts
=> fix: 삭제된 여행은 북마크 리스트에 나오지 않도록함

src/api/bookmark/bookmark.service.ts
=> fix: 북마크 리스트 아이디 값은 travelId로 변경
